### ISSUE TITLE
Add support for Travis CI for testing

### ISSUE THREAD

**Issue by frozzare** [personnummer/swift#3]
It would be if we could add support for [Travis CI](https://travis-ci.org/) to enable automatic testing for this project. Documentation https://docs.travis-ci.com/user/languages/objective-c/

@arbitur you maybe know what the travis file should contain for a swift project?

**Comment by arbitur** [comment]
Ill look into this some other time, maybe this weekend or if Im very bored after work during workdays.

**Comment by GoranLilja** [comment]
I’ve started working on this.

**Comment by Johannestegner** [comment]
@GoranLilja Might even be easier to just throw in a github action script for it :)

**Comment by Johannestegner** [comment]
https://github.com/marketplace/actions/swift-setup

That one might be useful! :)

**Comment by GoranLilja** [comment]
I saw your comment too late, now I already implemented the support for Travis CI.
