### ISSUE TITLE
Maintainer wanted

### ISSUE THREAD

**Issue by frozzare** [personnummer/swift#7]
This package isn't maintained and we would like it to be maintained. We have a [spec](https://github.com/personnummer/meta) that should be followed. We're working on version 3 of the spec and will updated all packages that are maintained as soon as possible.

**Comment by GoranLilja** [comment]
I'm interested. Where do I sign up?

**Comment by frozzare** [comment]
@GoranLilja Great! Send me a e-mail (it's on my profile) with your e-mail and then I will invite you to our slack.
